name: Build APK

on:
  push:
    branches:
      - matagi

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Retrieve commit identification
      run: |
        GIT_HASH=$(git rev-parse --short HEAD)
        echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: gradle

    - name: Decode Keystore File
      run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > $GITHUB_WORKSPACE/key.keystore

    - uses: burrunan/gradle-cache-action@v1
      name: Build Release Gradle
      with:
        job-id: Dantotsu
        # Specifies arguments for Gradle execution
        arguments: |
          --configure-on-demand
          assembleGoogleMatagi
          -Pandroid.injected.signing.store.file=${{ github.workspace }}/key.keystore
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }}
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }}
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
        # Gradle version to use for execution:
        #   wrapper (default), current, rc, nightly, release-nightly, or
        #   versions like 6.6 (see https://services.gradle.org/versions/all)
        gradle-version: wrapper
        # Properties are passed as -Pname=value
        properties: |
          org.gradle.unsafe.configuration-cache=true

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
          name: Dantotsu-${{ env.GIT_HASH }}
          path: "app/build/outputs/apk/google/matagi/Dantotsu-${{ env.GIT_HASH }}-google-matagi.apk"

    - uses: keyfactor/action-delete-prereleases@main
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: 8bitDream/action-github-releases@v1.0.0
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.GIT_HASH }}
        prerelease: true
        title: Dantotsu-${{ env.GIT_HASH }}
        files: |
          app/build/outputs/apk/google/matagi/Dantotsu-${{ env.GIT_HASH }}-google-matagi.apk
